In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Car Dataset Processed.csv")

In [4]:
df.columns

Index(['Unnamed: 0', 'car_name', 'registration_year', 'insurance_validity',
       'fuel_type', 'seats', 'kms_driven', 'ownsership', 'transmission',
       'manufacturing_year', 'mileage(kmpl)', 'engine(cc)', 'max_power(bhp)',
       'torque(Nm)', 'price(in lakhs)'],
      dtype='object')

In [5]:
df.head(2)

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.40,999.0,999.0,9863.0,8.99

In [6]:
df['insurance_validity'].value_counts()

insurance_validity
Comprehensive            1081
Third Party insurance     289
Zero Dep                   64
Third Party                63
Not Available               2
Name: count, dtype: int64

In [7]:
df['insurance_validity'] = df['insurance_validity'].map({'Comprehensive':0,'Third Party insurance':1, 'Zero Dep':2, 'Not Available':3, 'Third Party':1})

In [8]:
df['insurance_validity'].value_counts()

insurance_validity
0    1081
1     352
2      64
3       2
Name: count, dtype: int64

In [9]:
df['fuel_type'].value_counts()

fuel_type
Petrol    997
Diesel    480
CNG        22
Name: count, dtype: int64

In [10]:
df['fuel_type']=df['fuel_type'].map({'Petrol':0, 'Diesel':1, 'CNG':2})

In [11]:
df['fuel_type'].value_counts()

fuel_type
0    997
1    480
2     22
Name: count, dtype: int64

In [12]:
df['ownsership'].value_counts()

ownsership
First Owner     1236
Second Owner     240
Third Owner       21
Fifth Owner        2
Name: count, dtype: int64

In [13]:
df['ownsership']=df['ownsership'].map({'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fifth Owner':5})

In [14]:
df['ownsership'].value_counts()

ownsership
1    1236
2     240
3      21
5       2
Name: count, dtype: int64

In [15]:
df['transmission'].value_counts()

transmission
Manual       832
Automatic    667
Name: count, dtype: int64

In [16]:
df['transmission']=df['transmission'].map({'Manual':0, 'Automatic':1})

In [17]:
df['transmission'].value_counts()

transmission
0    832
1    667
Name: count, dtype: int64

In [18]:
df['registration_year']

0       Jul-17
1       Jan-21
2       Sep-18
3       Dec-19
4       Aug-19
         ...
1494    May-22
1495    Aug-20
1496    Jun-17
1497    May-18
1498    May-18
Name: registration_year, Length: 1499, dtype: object

##### Extract only the year part from the registration year

In [19]:
df['registration_year']=df['registration_year'].str[-2:]

In [20]:
df['registration_year'].value_counts()

registration_year
18    233
17    189
19    181
16    136
15    131
20    126
21    109
22    100
14    100
12     51
13     47
23     44
11     23
10     17
09     11
07      1
Name: count, dtype: int64

##### PHASE 1 : Select input features

In [21]:
X = df[['insurance_validity','fuel_type','kms_driven','ownsership','transmission']]
y = df['price(in lakhs)']

In [22]:
X.head()

   insurance_validity  fuel_type  kms_driven  ownsership  transmission
0                   0          0       56000           1             1
1                   0          0       30615           1             1
2                   0          1       24000           1             1
3                   0          0       18378           1             0
4                   0          0       44900           1             1

In [23]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

In [24]:
models = {'LinReg':LinearRegression(),
         'KNN-3':KNeighborsRegressor(n_neighbors = 3),
         'SVM-Poly':SVR(kernel='poly')}

for name,model in models.items():
    model.fit(X,y)
    sc = model.score(X,y)
    print(name , sc)

LinReg 0.01881841973825704
KNN-3 0.5927605118086187
SVM-Poly -0.002159341825328953

In [25]:
final_model = models['KNN-3']

In [26]:
d1={'Comprehensive':0, 'Third Party insurance':1, 'Zero Dep':2, 'Not Avaliable': 3, 'Third Party': 1}
d2={'Petrol': 0, 'Diesel': 1, 'CNG':2}
d3={'Manual':0, 'Automatic':1}
d4={'First Owner':1, 'Second Owner':2, 'Third Owner': 3, 'Fifth Owner': 5, 'Fourth Owner': 4}

In [27]:
insurance_validity = input("Enter insurance_validity: ")
fuel_type = input('fuel_type')
kms_driven=input('kms_driven')
ownsership=input('Ownsership')
transmission=input('Transmission Type')
insurance_validity=d1[insurance_validity]
fuel_type=d2[fuel_type]
transmission=d3[transmission]
ownsership=d4[ownsership]
kms_driven=int(kms_driven)
test = [[insurance_validity, fuel_type, kms_driven, ownsership, transmission]]
yp=int(final_model.predict(test)[0])

Enter insurance_validity:  Zero Dep
fuel_type Petrol
kms_driven 35000
Ownsership First Owner
Transmission Type Automatic

C:\Users\RUJUTA\anaconda3\envs\streamlit_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(

In [28]:
print('Predicted Car price is {} Rs. '.format(yp))

Predicted Car price is 26 Rs.

In [29]:
import pickle
pickle.dump(final_model,open('final_model.pkl','wb'))